function soma(n1=0, n2=0) { /* FOI COLOCADO O "0" PARA SE UM PARAM. NÃO FOR DEFINIDO NA CHAMADA, O CALCULO FUNCIONAR MSM ASSIM */
   return n1 + n2; //VAI RETORNAR O PARAM.1 + PARAM.2
}
console.log(soma(240, 189))//VAI EXIBIR O RETORNO DA AÇÃO